
SEARCHES_NUMBER = 3
WRITER_AGENT_MODEL = "gpt-4o-mini"
RECIPIENT_NAME_COLUMN = "Nombre"
RECIPIENT_EMAIL_COLUMN = "Correo"
EMAIL_REGEX_PATTERN = r"^[^@\s]+@[^@\s]+\.[^@\s]+$"
EMAIL_SERVER = "smtp.gmail.com"
EMAIL_SERVER_PORT = 587